{
 "title": "FastAPI MLOps (PM2.5) - Overview",
 "tags": [
  "mlops",
  "fastapi",
  "prometheus"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests / sec (all)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Predictions / sec",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(predictions_total[1m]))"
    }
   ]
  },
  {
   "title": "p95 Latency (ms)",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[5m])) by (le)) * 1000"
    }
   ]
  },
  {
   "title": "Request rate by endpoint",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total[1m])) by (endpoint)"
    }
   ]
  },
  {
   "title": "Latency (p50/p95/p99) ms",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 13, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_latency_seconds_bucket[5m])) by (le)) * 1000"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket[5m])) by (le)) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_latency_seconds_bucket[5m])) by (le)) * 1000"
    }
   ]
  }
 ]
}